version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:SED_TARGET_AWS_REGION:SED_TARGET_AWS_ACCOUNT_ID:task-definition/app-A-SED_TARGET_ENVIRONMENT"
        LoadBalancerInfo:
          ContainerName: "app-A-nginx-SED_TARGET_ENVIRONMENT"
          ContainerPort: "80"